application: sdsfoodbot
runtime: python27
api_version: 1
threadsafe: true
version: 1 #필수

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- env/